# Example pre-commit-config.yaml that can be added to your repo
repos:
  # SAST: Configuration
  - repo: https://github.com/jonny-wg2/pre-commit-sast
    rev: bf2ab7d452c8557b5be44dabe25d09946a785d4e
    hooks:
      - id: trivyconfig
        args:
          - "--args=--severity HIGH,CRITICAL"
      - id: validate-pre-commit-revs
  # SAST: Semgrep
  - repo: https://github.com/returntocorp/semgrep
    rev: 8b4b26313328afdbbb30470cc09d3b7de643e7e6
    hooks:
      - id: semgrep
        name: "SAST:semgrep-ci (exclude findings with commenting) [# nosemgrep]"
        exclude: ".+test.+$|.+presentations.+$"
        args: [
            "--config=p/ci", # --config=p/owasp-top-ten
            "--severity=ERROR", # info, warning, or error
            "--exclude-rule=go.grpc.security.grpc-server-insecure-connection.grpc-server-insecure-connection",
            "--error", # Exit 1 if there are findings
          ]
        types_or:
          [
            javascript,
            go,
            python,
            java,
            kotlin,
            ts,
            bash,
            terraform,
            dockerfile,
          ]
        stages: [commit]
  # SAST: Erlang Pest https://github.com/okeuday/pest
  - repo: https://github.com/omnicate/pre-commit-erlang-pest
    rev: b878bf7314d7537c69cbcbb17d7e45a928e27ae6
    hooks:
      - id: pest
  - repo: https://github.com/syntaqx/git-hooks
    rev: a3b888f92cd5b40b270c9a9752181fdc1717cbe5
    hooks:
      - id: shellcheck
